"""add must_change_password to users table for security

Revision ID: f0f89f0bbfc6
Revises: 2dfe675e9df3
Create Date: 2025-10-20 15:52:38.881119

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f0f89f0bbfc6"
down_revision: Union[str, None] = "2dfe675e9df3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column with default value for existing rows
    op.add_column(
        "users",
        sa.Column(
            "must_change_password", sa.Boolean(), nullable=True, server_default="false"
        ),
    )

    # Set default for existing users (demo accounts don't need to change password)
    op.execute(
        "UPDATE users SET must_change_password = false WHERE must_change_password IS NULL"
    )

    # Now make it NOT NULL
    op.alter_column("users", "must_change_password", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "must_change_password")
    # ### end Alembic commands ###
