"""add must_change_password to users table for security

Revision ID: f0f89f0bbfc6
Revises: 2dfe675e9df3
Create Date: 2025-10-20 15:52:38.881119

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f0f89f0bbfc6"
down_revision: Union[str, None] = "2dfe675e9df3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_gameplay_states_gameplay_id", table_name="gameplay_states", if_exists=True
    )
    op.drop_index(
        "ix_gameplay_states_last_played_at",
        table_name="gameplay_states",
        if_exists=True,
    )
    op.drop_index(
        "ix_gameplay_states_room_id", table_name="gameplay_states", if_exists=True
    )
    op.drop_table("gameplay_states", if_exists=True)

    # Add column with default value for existing rows
    op.add_column(
        "users",
        sa.Column(
            "must_change_password", sa.Boolean(), nullable=True, server_default="false"
        ),
    )

    # Set default for existing users (demo accounts don't need to change password)
    op.execute(
        "UPDATE users SET must_change_password = false WHERE must_change_password IS NULL"
    )

    # Now make it NOT NULL
    op.alter_column("users", "must_change_password", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "must_change_password")
    op.create_table(
        "gameplay_states",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("room_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "gameplay_id", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "state",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "last_played_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.id"],
            name="gameplay_states_room_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="gameplay_states_pkey"),
        sa.UniqueConstraint("room_id", "gameplay_id", name="unique_room_gameplay"),
    )
    op.create_index(
        "ix_gameplay_states_room_id", "gameplay_states", ["room_id"], unique=False
    )
    op.create_index(
        "ix_gameplay_states_last_played_at",
        "gameplay_states",
        ["last_played_at"],
        unique=False,
    )
    op.create_index(
        "ix_gameplay_states_gameplay_id",
        "gameplay_states",
        ["gameplay_id"],
        unique=False,
    )
    # ### end Alembic commands ###
